[package]
name = "backup"
version = "0.1.0"
edition = "2024"
publish = false
authors = ["RÃ©mi Bardon <remi@remibardon.name>"]

[dependencies]
anyhow = { version = "=1.0.99", default-features = false }
bytes = { version = "=1.11.0", default-features = false, features = ["std"] }
sequoia-openpgp = { version = "=2.1.0", default-features = false, features = ["crypto-nettle"] }
sha2 = { version = "=0.10.9", default-features = false }
tar = { version = "=0.4.44", default-features = false }
thiserror = { version = "=2.0.17", default-features = false }
time = { version = "=0.3.44", default-features = false }
tokio = { version = "=1.47.1", default-features = false, features = [
    "io-util",
    "macros",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
] }
zstd = { version = "=0.13.3", default-features = false }

# Optional dependencies.
aws-sdk-s3 = { optional = true, version = "=1.115.0", default-features = false, features = [
    "default-https-client",
    "rt-tokio",
    "rustls",
    "sigv4a",
] }

[lib]
name = "prose_backup"

[[bin]]
name = "backup"
path = "src/main.rs"
required-features = ["destination_fs"]

[features]
default = ["destination_s3"]
test = ["destination_fs"]
destination_fs = []
destination_s3 = ["dep:aws-sdk-s3"]
